-- Basic SELECT operations
SELECT * FROM TBLOGRENCILER;
SELECT OGRAD, OGRSOYAD FROM TBLOGRENCILER;
SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR = 'Ankara';

-- Insert Examples
INSERT INTO TBLOGRENCILER (OGRAD, OGRSOYAD, OGRSEHIR)
VALUES ('Demirhan', 'Abay', 'Ankara');

-- Update Example
UPDATE TBLOGRENCILER SET OGRKULUP = 'Satranç' WHERE OGRAD = 'Demirhan';

-- Delete Example
DELETE FROM TBLDERSLER WHERE DERSAD = 'Tarih';

-- Aggregate Functions
SELECT COUNT(*) AS 'Toplam Kayıt' FROM TBLOGRENCILER;
SELECT AVG(SINAV1) FROM TBLNOTLAR;
SELECT MAX(SINAV1), MIN(SINAV1) FROM TBLNOTLAR;

-- Group By
SELECT OGRSEHIR, COUNT(*) AS 'Öğrenci Sayısı'
FROM TBLOGRENCILER
GROUP BY OGRSEHIR;

-- LIKE Examples
SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE '%a%';

-- Distinct
SELECT DISTINCT OGRSEHIR FROM TBLOGRENCILER;

-- IN Operator
SELECT * FROM TBLOGRENCILER 
WHERE OGRSEHIR IN ('Ankara','Bursa','Üsküp');

-- BETWEEN Operator
SELECT * FROM TBLNOTLAR WHERE ORTALAMA BETWEEN 75 AND 100;

-- JOIN Example
SELECT NOTID, OGRAD + ' ' + OGRSOYAD AS 'Ad Soyad',
       DERSAD, SINAV1, SINAV2, SINAV3, ORTALAMA
FROM TBLNOTLAR
INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID;

-- STRING FUNCTIONS
SELECT UPPER(OGRAD) FROM TBLOGRENCILER;
SELECT LEFT(OGRAD,1) + '.' + OGRSOYAD FROM TBLOGRENCILER;

-- MATH FUNCTIONS
SELECT POWER(2,4) AS 'Üs Alma';
SELECT SQRT(625) AS 'Karekök';
SELECT ABS(-85) AS 'Mutlak Değer';
