-- DATABASE SCHEMA

-- Kategori Tablosu
CREATE TABLE TBLKATEGORI
(
    KATEGORIID TINYINT IDENTITY(1,1) PRIMARY KEY,
    KATEGORIAD VARCHAR(50)
);

-- Ürünler Tablosu
CREATE TABLE TBLURUNLER
(
    URUNID INT IDENTITY (1,1) PRIMARY KEY,
    URUNAD VARCHAR(50),
    URUNMARKA VARCHAR(50),
    KATEGORI TINYINT,
    URUNALISFIYAT DECIMAL(18,2),
    URUNSATISFIYAT DECIMAL(18,2),
    URUNSTOK SMALLINT CHECK (URUNSTOK > 0),
    URUNDURUM BIT DEFAULT '1'
);

-- Personel Tablosu
CREATE TABLE TBLPERSONEL
(
    PERSONELID SMALLINT IDENTITY(1,1) PRIMARY KEY,
    PERSONELADSOYAD VARCHAR(50)
);

-- Müşteri Tablosu
CREATE TABLE TBLMUSTERI
(
    MUSTERIID INT PRIMARY KEY IDENTITY(1,1),
    MUSTERIAD VARCHAR(50),
    MUSTERISOYAD VARCHAR(50),
    MUSTERISEHIR VARCHAR(13),
    MUSTERIBAKIYE DECIMAL(18,2)
);

-- Hareket (Satış) Tablosu
CREATE TABLE TBLHAREKET
(
    HAREKETID INT PRIMARY KEY IDENTITY(1,1),
    URUN INT,
    MUSTERI INT,
    PERSONEL SMALLINT,
    ADET INT,
    TUTAR DECIMAL (18,2),
    TARIH SMALLDATETIME
);
