-- STORED PROCEDURES

-- Product Listing Procedure
ALTER PROCEDURE URUNGETIR
@Deger VARCHAR(50) = 'BUZDOLABI'
AS
SELECT URUNAD, URUNSTOK, URUNMARKA
FROM TBLURUNLER
WHERE URUNAD = @Deger;


-- Sales Movement Procedure
ALTER PROCEDURE HAREKETLER
AS
SELECT 
    HAREKETID,
    URUNAD,
    LEFT(MUSTERIAD,1) + '.' + MUSTERISOYAD AS 'Müşteri',
    PERSONELADSOYAD,
    ADET,
    TUTAR,
    TARIH
FROM TBLHAREKET
INNER JOIN TBLURUNLER ON TBLHAREKET.URUN = TBLURUNLER.URUNID
INNER JOIN TBLMUSTERI ON TBLHAREKET.MUSTERI = TBLMUSTERI.MUSTERIID
INNER JOIN TBLPERSONEL ON TBLHAREKET.PERSONEL = TBLPERSONEL.PERSONELID;

